### ISSUE TITLE
upgrade to 2.16 BSP

### ISSUE THREAD

**Issue by mbinoy** [igel-oss/meta-rcar#1]
hi,

its nice and helpful, do you have plan to upgrade to the R-car BSP version 2.1.6?

Best regards,
Binoy

**Comment by dhobsong** [comment]
Hi Binoy,

I'm glad that you have found this helpful.  To answer your question, yes, we do plan to upgrade to the latest BSP, and to update the Chromium version too.  We haven't had time to look at it yet, but we'll probably start next month or so.

**Comment by mbinoy** [comment]
Thanks Damian,

I was able to integrate and use this in 2.16 BSP

We can close the ticket for now

best regards,
Binoy
